### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by GeneralJarrett97** [Muzi-Chan/MonikAI#3]
I am interested in adding dialogue but I'm not quite sure how to implement it. Do I need to do anything more than add to the .csv files? Sorry if it's too simple a question or if there was another way I should go about asking

**Comment by Lytasia** [comment]
Hey ! Sorry for the late answer, didn't saw the issue
Thanks for being interessed to help MonikAI grow, It's not "too simple" at all, The .csv is all you need for dialogue

I'll do soon a guide for how to contribute
