### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by 222killer222** [Muzi-Chan/MonikAI#4]
Hello there, I wanted to add the browser extension so that Monika could react to what I do on the browser. I have noticed sadly that the link that referred to it didnt work. is this a problem on my part or yours?

**Comment by stake2** [comment]
Use the Firefox browser extension on the zip, search on the internet on how to install an extension using a Zip file:
https://github.com/Lytasia/MonikAI/blob/master/BrowserPlugin/Firefox_Plugin.zip

**Comment by Muzi-Chan** [comment]
I'll mark this issue as closed, since the browser extension will be redone anyway
