### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by naenaebabyy** [Muzi-Chan/MonikAI#9]
It opens, saying "An error has occured while updating MonikAI: response status code does not indicate success: 404 (not found)." then "An error has occured loading MonikAI data. Are you connected to the internet? If you disable Auto-Update in the settings you don't need to be connected to the internet when MonikAI launches. NOTE: If this is your first time launching MonikAI, you need to be connected to the internet regardless!" 

Edition Windows 10 Home

Version 20H2

Installed on ‎19/‎03/‎21

OS build 19042.1110

Experience Windows Feature Experience Pack 120.2212.3530.0

**Comment by Muzi-Chan** [comment]
I figured the problem out, I forgot to update the code when I changed my Github username, so it was searching the file on the old one, which doesn't exist, I'm doing a update to fix it, download MonikAI again when I close this issue and you will be good

Thanks for submitting, and doing it correctly :D

**Comment by Muzi-Chan** [comment]
It's done, you can download again.

**Comment by Muzi-Chan** [comment]
After my PC doing shit I don't understand, it's fixed, thanks for reporting !
